services:
  db:
    build: .
    container_name: postgresdb_preppal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: preppal_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - llm-rag-network  # Connect to llm-rag-network

volumes:
  db_data:

networks:
  llm-rag-network:
    external: true  # Specify that this is an external network
