name: "Test API Dockerfile structure"

on:
  push:
    branches:
      - main
      - milestone4
      - milestone5

jobs:
  dockerfile-test:
    runs-on: macos-13

    steps:
      # Step 1: Check out the source code
      - name: Checkout source
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build Docker image
        working-directory: src/apiservice
        run: |
          docker build -t test-api-image:latest -f Dockerfile .

      # Step 3: Download and Install Container Structure Test
      - name: Install Container Structure Test
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-darwin-amd64
          chmod +x container-structure-test-darwin-amd64
          sudo mv container-structure-test-darwin-amd64 /usr/local/bin/container-structure-test

      # Step 4: Run Container Structure Tests
      - name: Run Container Structure Tests
        timeout-minutes: 20
        working-directory: src/apiservice
        run: |
          container-structure-test test \
            --image test-api-image:latest \
            --config tests/docker_test.yml

      # Step 5: Delete Docker image
      - name: Cleanup Docker image
        run: docker image rm test-api-image:latest || echo "Image not found, skipping cleanup"
